### ISSUE TITLE
 POC Kyma operator II - refactor Kyma CR management

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/kyma-operator#91]
### AC
- [x] Kyma CR is synchronised from SKR as Single-Source-Of-Truth
    - [x] ~~Deleted CRs on SKR gets recreated from KCP CR~~(handled in https://github.com/kyma-project/kyma-operator/issues/90)
    - [x] If KCP CR is deleted, Kyma installation gets uninstalled
    - [x] ~~Ignore Update on Kyma CR spec from KCP to SKR~~
    - [x] #93: Remove Logic for Configuration Overrides in Kyma CR and passing the Label Selector to Manifest Operator
    - [x] #95
- [x] Status aggregation works by combining all manifest CR with all module-CR states and writing it into the Kyma status (allignment blocked by changes necessary in https://github.com/kyma-project/kyma-operator/issues/90 to create multiple paths for SKR/KCP Installation first)
  - [x] CRDs are verified to contain `status.state`-field

### Developer Notes
- Refactor `kyma_synchronization_context.go`
  - Refactor `SynchronizeRemoteKyma` only keep the logic sync from SKR to KCP
- [x] Write tests to verify if status aggregation works

**Comment by jakobmoellersap** [comment]
CRDs verified in https://github.com/kyma-project/kyma-operator/pull/92

**Comment by jakobmoellersap** [comment]
I would argue we do not actually remove the synchronization from KCP. My argument for this is that it currently does not hurt and I could not realiably find issues with the Synchronization Context. Instead I would write an automated test for this that confirms the sync wouldn't be an issue in most cases and refactor only the Sync to not call the remote api server in every case for setting annotations and generated timestamps.

**Comment by jakobmoellersap** [comment]
Configuration Override Removal in https://github.com/kyma-project/kyma-operator/pull/93
